HOST: http://www.google.com/

--- OSDI ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
API Endpoint

--

Get the API Endpoint
GET /api/v1
< 200
< Content-Type: application/json

	{
	  "motd": "Welcome to the ACME Action Platform OSDI API endpoint!!",
	  "capabilities" : {
		"osdi:rest-read" : true,
		"osdi:actions" : true,
		"osdi:rest-write" : true,
		"acme:defeat_opponent": {								"modes" : [
				"landslide", "nailbiter"
			]
		},
	

	  "_links": {
	    "curies": [
			{"name": "osdi", "href": "http://api.opensupporter.org/docs/v1/{rel}", "templated": true },
			{"name": "acme", "href": "http://acme.foo/"}
		],  
	    "osdi:people": {
	      "href": "/api/v1/people",
	    },
		"osdi:people_lists": {
	      "href": "/api/v1/people_lists",
	    },
	    "osdi:addresses": {
	      "href": "/api/v1/addresses",
	    },
	    "odsi:questions": {
	      "href": "http://api.opensupporter.org/api/v1/questions",
	    },
	    "osdi:question_answers": {
	      "href": "http://api.opensupporter.org/api/v1/question_answers",
	    },
	    "self": {
	      "href": "/api/v1",
	    }
	  }
	}

Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created",
  "url": "/shopping-cart/2" 
}

-- Donation Resources --

This resource allows you to submit payment information to process your *shopping cart* items
POST /api/v1/donations
{ 
    "amount": "50.00", "currency": "usd",
    "person" : {
            "given_name" : "John",
            "family_name" : "Doe"
    }
}
< 200
{ "receipt": "/payment/receipt/1" }